FROM sh-artifactory.sh.shaam.gov.il:8082/docker/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443
COPY crt/*.crt /usr/local/share/ca-certificates/
RUN update-ca-certificates

FROM sh-artifactory.sh.shaam.gov.il:8082/docker/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ./TaxCalculator.csproj .
RUN dotnet nuget add source http://sh-artifactory.sh.shaam.gov.il:8082/artifactory/api/nuget/v3/nuget -n artifactory 
RUN dotnet nuget disable source nuget.org
RUN dotnet restore --interactive
COPY . .
RUN rm -r ./DpSchema
RUN dotnet build "./TaxCalculator.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "TaxCalculator.csproj" -c Release -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "TaxCalculator.dll"]